# Generated by Django 5.1.7 on 2025-05-12 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('quick', 'Quick'), ('salary', 'Salary'), ('emergency', 'Emergency'), ('multipurpose', 'Multipurpose')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.IntegerField()),
                ('grace', models.IntegerField()),
                ('payment_start_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('reject', 'Reject')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'tblLoans',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('branch_of_service', models.CharField(choices=[('Armed Forces', 'Armed Forces'), ('Philippine Coast Guard', 'Philippine Coast Guard'), ('Philippine Army', 'Philippine Army'), ('Philippine Marine Corps', 'Philippine Marine Corps'), ('Bureau of Fire Protection', 'Bureau of Fire Protection'), ('Philippine Navy', 'Philippine Navy'), ('Bureau of Jail Management and Penology', 'Bureau of Jail Management and Penology'), ('Philippine Coast Guard', 'Philippine Cost Guard')], max_length=100)),
                ('service_no', models.CharField(max_length=50, unique=True)),
                ('office_business_address', models.TextField()),
                ('unit_assignment', models.CharField(max_length=255)),
                ('unit_office_telephone_no', models.CharField(blank=True, max_length=20)),
                ('occupation_designation', models.CharField(max_length=100)),
                ('source_of_income', models.CharField(max_length=100)),
                ('member_signature', models.TextField(blank=True, null=True)),
                ('member_picture', models.ImageField(blank=True, null=True, upload_to='member_pictures/')),
            ],
            options={
                'db_table': 'tblMember',
            },
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amortization', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loans')),
            ],
            options={
                'db_table': 'tblAmortization',
            },
        ),
        migrations.AddField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.member'),
        ),
    ]
